apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-2
  namespace: default
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    volumeMounts:
    - name: nginxconf
      mountPath: /data/
      readOnly: true
  volumes:
  - name: nginxconf
    secret:
      secretName: mysql-root-pass

#下面是通过环境变量注入信息
#    env:
#    - name: MYSQL_ROOT_PASSWORD
#      valueFrom: 
#        secretKeyRef:
#          name: mysql-root-pass
#          key: password
