apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-nginx-01
  name: secret-nginx-01
spec:
  volumes:
  - name: xx
    secret:
      secretName: mysecret1
  containers:
  - image: nginx
    name: secret-nginx
    volumeMounts:
    - name: xx
      mountPath: "/etc/xx"
      readOnly: true
