apiVersion: v1
kind: Namespace
metadata:
  name: pv-test


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-01
  labels:
    name: pv01
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Recycle
# storageClassName: slow  ##这是一个存储类，此环境中不支持。
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path:  "/data/pv01"
    server: storage01.sunlge.com

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-01
  namespace: pv-test
spec:
  accessModes: ["ReadWriteMany"]
  volumeMode: Filesystem
##要求空间大小最少请求资源字段
  resources:
    requests:
      storage: 1Gi
#  storageClassName: slow
  selector:
    matchLabels:
      name: pv01

---
apiVersion: v1
kind: Pod
metadata:
  namespace: pv-test
  name: vol-pvc-pod
  labels:
    app: pvc-test
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: html
  volumes:
  - name: html
    persistentVolumeClaim:
      claimName: pvc-nfs-01
      readOnly: false

#下面是绑定存储卷pv的写法
#    - name: html
#      nfs:
#        server: storage01.sunlge.com
#        path: /data/pv01
