apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: jenkins-deploy
  name: jenkins-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jenkins-pod
  template:
    metadata:
      labels:
        run: jenkins-pod
    spec:
      containers:
      - image: jenkins:latest
        name: jenkins-test
        resources: {}
