apiVersion: v1
kind: Pod
metadata:
  name: pod-use
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
  hostNetwork: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: myapp-test
  name: myapp-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: myapp-test01
  strategy: {}
  template:
    metadata:
      labels:
        run: myapp-test01
    spec:
      containers:
      - image: ikubernetes/myapp:v1
        name: myapp-v1
      - image: busybox
        name: myapp-v2
        command:
        - "/bin/sh"
        - "-c"
        - "sleep 3600"
