apiVersion: v1
kind: Service
metadata:
  name: nginx-svc3
  labels:
    run: nginx-svc3
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-deploy
  sessionAffinity: None
  type: ClusterIP
