apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: sunlge-test
  name: sunlge-test
spec:
  replicas: 4
  selector:
    matchLabels:
      run: sunlge-test
  strategy: {}
  template:
    metadata:
      labels:
        run: sunlge-test
    spec:
      containers:
      - image: ikubernetes/myapp:v1
        name: sunlge-test
        ports:
        - name: http
          containerPort: 80
      tolerations: 
      - key: "DiskType"
        operator: "Equal"
        value: "ssd"
        effect: "NoSchedule"

#设置以下污点容忍度可以将Pod调度至master上
#      tolerations:
#      - key: "node-role.kubernetes.io/master"
#        operator: "Exists"
#        effect: "NoSchedule"
#        tolerationSeconds: 10

#节点标签选择，可将Pod调度至拥有disk=ssd标签的节点
#      nodeSelector:
#        disk: ssd

#节点污点的三种终态，taint的effect定义对Pod排斥效果:
#      NoSchedule: 一定不能被调度,已经调度上的Pod将不在驱除
#      PreferNoSchedule: 尽量不要调度
#      NoExecute: 不仅不会调度, 还会驱逐Node上已有的Pod立即驱除
#        
#管理节点污点：
#        kubectl taint node node01.sunlge.com node-type=production:NoSchedule
#        kubectl taint node node1 key1:NoSchedule-  # 这里的key可以不用指定value
#        kubectl taint node node1 key1:NoExecute-
#        kubectl taint node node1 key1-  删除指定key所有的effect
#        kubectl taint node node1 key2:NoSchedule-
