apiVersion: v1
kind: Pod
metadata:
  name: pod-nodeaffinity-demo
  namespace: default
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
  affinity:
    nodeAffinity:
##下面这个preferred选择策略不是必须的。
#       preferredDuringSchedulingIgnoredDuringExecution:
#       - preference:
#           matchExpressions:
#           - key: zone
#             operator: In
#             values:
#             - foo
#             - bar
#         weight: 60
#
##这个required选择策略，策略中的规则是必须存在的
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: zone
              operator: In
              values:
              - foo
              - bar
