apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-01
  labels:
    name: pv01
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Recycle
# storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path:  "/data/pv01"
    server: storage01.sunkge.com
